version: '3.8'

services:
  frontend:
    image: saif8957/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: saif8957/backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env # This line ensures that the environment variables are loaded

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
